<%@ Page Title="" Language="C#" MasterPageFile="~/Home.Master" AutoEventWireup="true" CodeBehind="FrmRegConsulta.aspx.cs" Inherits="Trabalho_de_Avaliação_B.FrmRegConsulta" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
	<style type="text/css">
	.auto-style12 {
		width: 100%;
			height: 234px;
			margin-left:10px;
		}
	.auto-style14 {
		width: 129px;
	}
		.auto-style16 {
			width: 127px;
		}
		.auto-style17 {
			width: 179px;
		}
		.auto-style18 {
			width: 206px;
		}
		.auto-style19 {
			text-align: center;
		}
	</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
	<asp:Button ID="Button2" runat="server" Text="Registar Consulta" OnClick="Button2_Click" />
	<br />
	<br />
	<asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="NumCons" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True">
		<Columns>
			<asp:BoundField DataField="NumCons" HeaderText="NumCons" InsertVisible="False" ReadOnly="True" SortExpression="NumCons" />
			<asp:BoundField DataField="DataCons" HeaderText="DataCons" SortExpression="DataCons" />
			<asp:BoundField DataField="NMed" HeaderText="NMed" SortExpression="NMed" />
			<asp:BoundField DataField="NPac" HeaderText="NPac" SortExpression="NPac" />
			<asp:BoundField DataField="ValorCon" HeaderText="ValorCon" SortExpression="ValorCon" DataFormatString="{0:###.##}€" />
			<asp:BoundField DataField="MotivoDaConsulta" HeaderText="MotivoDaConsulta" SortExpression="MotivoDaConsulta" />
		</Columns>
	</asp:GridView>
	<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:L1949_ConnectionString %>" SelectCommand="SELECT [NumCons], [DataCons], [NMed], [NPac], [ValorCon], [MotivoDaConsulta] FROM [Tbl_Consulta]"></asp:SqlDataSource>
	<br />
	<asp:Panel ID="Panel1" runat="server" style="margin-left:10px">
		<table class="auto-style12">
			<tr>
				<td>&nbsp;</td>
				<td class="auto-style16">
					<asp:Label ID="Label3" runat="server" Text="Data Consulta:"></asp:Label>
					<asp:TextBox ID="txtData" runat="server" TextMode="Date" Width="104px"></asp:TextBox>
				</td>
				<td>
					<asp:Label ID="Label4" runat="server" Text="Nome Doutor:"></asp:Label>
					<asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSource3" DataTextField="NomeMed" DataValueField="NumMed">
					</asp:DropDownList>
					<asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:L1949_ConnectionString %>" SelectCommand="SELECT [NumMed], [NomeMed] FROM [Tbl_Medicos]"></asp:SqlDataSource>
				</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td class="auto-style16">
					<asp:Label ID="Label5" runat="server" Text="Nome Paciente:"></asp:Label>
					<asp:DropDownList ID="DropDownList2" runat="server" DataSourceID="SqlDataSource2" DataTextField="NomePac" DataValueField="NumPac">
					</asp:DropDownList>
					<asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:L1949_ConnectionString %>" SelectCommand="SELECT [NumPac], [NomePac] FROM [Tbl_Pacientes]"></asp:SqlDataSource>
				</td>
				<td class="auto-style14">
					<asp:Label ID="Label7" runat="server" Text="Valor de Consulta:"></asp:Label>
					<asp:TextBox ID="TextBox3" runat="server" Width="104px"></asp:TextBox>
				</td>
				<td>&nbsp;</td>
			</tr>
			<tr >
				<td>&nbsp;</td>
				<td class="auto-style16">
					<asp:Label ID="Label6" runat="server" Text="Motivo da Consulta:"></asp:Label>
				</td>
				<td colspan="3">
					<asp:TextBox ID="TextBox5" runat="server" Height="107px" MaxLength="100" TextMode="MultiLine" Width="75%"></asp:TextBox>
				</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td class="auto-style19" colspan="4">
					<asp:Button ID="Button3" runat="server" OnClick="Button3_Click" Text="Adiciona Consulta" Width="174px" />
				</td>
				<td>&nbsp;</td>
			</tr>
		</table>
	</asp:Panel>
	
</asp:Content>
