<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage/Home.Master" AutoEventWireup="true" CodeBehind="FrmManutencao.aspx.cs" Inherits="Trabalho_de_Avaliação_B.FrmManutencao" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
	<style type="text/css">
		.auto-style12 {
			width: 100%;
		}

		.auto-style58 {
			width: 171px;
		}

		.auto-style18 {
			width: 103px;
		}

		.auto-style21 {
			width: 188px;
		}

		.auto-style25 {
			width: 198px;
			height: 29px;
		}

		.auto-style28 {
			height: 29px;
		}

		.auto-style30 {
			width: 218px;
			height: 29px;
		}
		.auto-style59 {
			width: 103px;
			height: 29px;
		}
	</style>
	<title>Manutenc&atilde;o Medico</title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
	<br />
	<asp:Button ID="Button2" runat="server" Text="Novo Medico" Width="100px" OnClick="Button2_Click" />
	<br />
	<br />
	<asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="NumMed" DataSourceID="SqlDataSource1" AutoGenerateColumns="False" OnRowUpdated="GridView1_RowUpdated" OnRowUpdating="GridView1_RowUpdating">
		<Columns>
			<asp:BoundField DataField="NumMed" HeaderText="Numero M&eacute;dicos" InsertVisible="False" ReadOnly="True" SortExpression="NumMed" />
			<asp:BoundField DataField="NomeMed" HeaderText="Nome M&eacute;dicos" SortExpression="NomeMed" />
			<asp:BoundField DataField="Especialidade" HeaderText="Especialidade" SortExpression="Especialidade" />
			<asp:TemplateField HeaderText="Sexo" SortExpression="Sexo">
				<EditItemTemplate>
					<asp:DropDownList ID="DropDownList2" runat="server" SelectedValue='<%# Bind("Sexo") %>' AutoPostBack="True">
						<asp:ListItem>F</asp:ListItem>
						<asp:ListItem>M</asp:ListItem>
					</asp:DropDownList>
				</EditItemTemplate>
				<ItemTemplate>
					<asp:Label ID="Label1" runat="server" Text='<%# Bind("Sexo") %>'></asp:Label>
				</ItemTemplate>
			</asp:TemplateField>
			<asp:BoundField DataField="NumOrdemMed" HeaderText="Numero da Ordem dos M&eacute;dicos" SortExpression="NumOrdemMed" />
			<asp:BoundField DataField="Telefone" HeaderText="Telefone" SortExpression="Telefone" />
		</Columns>
	</asp:GridView>
	<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:L1949_ConnectionString %>" SelectCommand="SELECT [NumMed], [NomeMed], [Especialidade], [Sexo], [NumOrdemMed], [Telefone] FROM [Tbl_Medicos]" DeleteCommand="Delete Tbl_Medicos where NumMed=@NumMed" UpdateCommand="Update Tbl_Medicos set NomeMed=@NomeMed, Especialidade=@Especialidade, Sexo=@Sexo, NumOrdemMed=@NumOrdemMed, Telefone=@Telefone where NumMed=@NumMed"></asp:SqlDataSource>
	<asp:Panel ID="Panel1" runat="server" Visible="false">
		<table class="auto-style12">
			<tr>
				<td class="auto-style18">&nbsp;</td>
				<td class="auto-style30">
					<asp:Label ID="Label3" runat="server" Text="Nome:"></asp:Label>
					<asp:TextBox ID="txtNome" runat="server" placeholder="Nome do Medico" MaxLength="50"></asp:TextBox>
				</td>
				<td class="auto-style18">&nbsp;</td>
				<td class="auto-style25">
					<asp:Label ID="Label5" runat="server" Text="Sexo:"></asp:Label>
					<asp:DropDownList ID="ddlSexo" runat="server" Selectedvalue='<%# Bind("Sexo") %>' AutoPostBack="True" Height="16px" Width="86px">
						<asp:ListItem>F</asp:ListItem>
						<asp:ListItem>M</asp:ListItem>
					</asp:DropDownList>
				
				</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td class="auto-style59"></td>
				<td class="auto-style30">
					<asp:Label ID="Label4" runat="server" Text="N&amp;deg; Ordem:"></asp:Label>
					<asp:TextBox ID="txtN" runat="server" placeholder="Numero Ordem dos Medico" MaxLength="9" TextMode="Number"></asp:TextBox>
				</td>
				<td class="auto-style59"></td>
				<td class="auto-style25">
					<asp:Label ID="Label6" runat="server" Text="Telefone:"></asp:Label>
					<asp:TextBox ID="txtFone" runat="server" placeholder="Telefone" MaxLength="9" TextMode="Number"></asp:TextBox>
				</td>
				<td class="auto-style28"></td>
			</tr>
			<tr>
				<td class="auto-style18">&nbsp;</td>
				<td class="auto-style30">
					<asp:Label ID="Label7" runat="server" Text="Especialidade:"></asp:Label>
					<asp:TextBox ID="txtEspe" runat="server" MaxLength="100" placeholder="Especialidade"></asp:TextBox>
				</td>
				<td class="auto-style58">&nbsp;</td>
				<td class="auto-style21">
					<asp:Button ID="Button3" runat="server" OnClick="Button3_Click" Text="Registar" Width="165px" />
				</td>
				<td>&nbsp;</td>
			</tr>
		</table>
	</asp:Panel>
</asp:Content>
